"""remove position from lessons

Revision ID: 0f8b3e6fb8b8
Revises: 973ca843e506
Create Date: 2026-07-22 17:48:42.072622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8b3e6fb8b8'
down_revision: Union[str, Sequence[str], None] = '973ca843e506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_created_by'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_is_active'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_module_active'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_constraint(op.f('uq_lessons_module_position'), 'lessons', type_='unique')
    op.drop_table_comment(
        'lessons',
        existing_comment='Stores lessons that belong to a module.',
        schema=None
    )
    op.drop_column('lessons', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False, comment='Display order of the lesson within the module.'))
    op.create_table_comment(
        'lessons',
        'Stores lessons that belong to a module.',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('uq_lessons_module_position'), 'lessons', ['module_id', 'position'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_index(op.f('ix_lessons_module_active'), 'lessons', ['module_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_lessons_is_active'), 'lessons', ['is_active'], unique=False)
    op.create_index(op.f('ix_lessons_created_by'), 'lessons', ['created_by'], unique=False)
    # ### end Alembic commands ###
