"""change in the quizes tables

Revision ID: 2673e555459e
Revises: f0b8dfe20896
Create Date: 2026-07-24 09:53:17.302568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2673e555459e'
down_revision: Union[str, Sequence[str], None] = 'f0b8dfe20896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('submission_status', sa.String(length=20), nullable=True, comment='ON_TIME or DELAYED, computed at submission time by comparing completed_at against enrollment.enrolled_at + quiz.duration_days. Null until the attempt is submitted.'))
    op.add_column('quiz_attempts', sa.Column('feedback', sa.Text(), nullable=True, comment='Instructor feedback for this quiz attempt.'))
    op.add_column('quiz_attempts', sa.Column('feedback_by', sa.UUID(), nullable=True, comment='Instructor who gave the feedback.'))
    op.add_column('quiz_attempts', sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True, comment='Time when the feedback was given.'))
    op.create_foreign_key('fk_quiz_attempts_feedback_by_users', 'quiz_attempts', 'users', ['feedback_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('quizzes', sa.Column('duration_days', sa.Integer(), nullable=True, comment="Number of days, counted from a student's enrollment date, within which this quiz must be submitted. The submission deadline for a student is enrollment.enrolled_at + duration_days."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'duration_days')
    op.drop_constraint('fk_quiz_attempts_feedback_by_users', 'quiz_attempts', type_='foreignkey')
    op.drop_column('quiz_attempts', 'feedback_at')
    op.drop_column('quiz_attempts', 'feedback_by')
    op.drop_column('quiz_attempts', 'feedback')
    op.drop_column('quiz_attempts', 'submission_status')
    # ### end Alembic commands ###
