"""create the EduGen LMS Tables

Revision ID: 35d22c5134e2
Revises: 
Create Date: 2026-07-21 15:38:51.144808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d22c5134e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key of the role.'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Unique role name (Admin, Instructor, Student).'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this role.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the role was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated this role.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the role was last updated.'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_roles_created_by_users', onupdate='CASCADE', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_roles_updated_by_users', onupdate='CASCADE', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name='pk_roles'),
    sa.UniqueConstraint('name'),
    comment='Stores all user roles available in the LMS.'
    )
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the user.'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Display username.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address used for login.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed user password.'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Role assigned to the user.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates whether the account is active.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this account.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the account was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated this account.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the account was last updated.'),
    sa.CheckConstraint('char_length(username) >= 3', name='ck_users_username_length'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_users_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role_id_roles', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_users_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the category.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique category name.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates whether the category is active.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this category.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the category was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated this category.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the category was last updated.'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_categories_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_categories_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_categories')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the course.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Course title displayed to learners.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed course description.'),
    sa.Column('language', sa.String(length=50), nullable=True, comment='Primary language of the course.'),
    sa.Column('duration', sa.String(length=50), nullable=True, comment='Estimated course duration.'),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='course_level_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Course price.'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='Category associated with this course.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates whether the course is active.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this course.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the course was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated this course.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the course was last updated.'),
    sa.CheckConstraint('price >= 0', name='ck_courses_price_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_courses_category_id_categories', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_courses_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_courses_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_courses')
    )
    op.create_index('ix_courses_category_id', 'courses', ['category_id'], unique=False)
    op.create_index('ix_courses_title', 'courses', ['title'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the certificate.'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='Student who earned the certificate.'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='Course associated with the certificate.'),
    sa.Column('certificate_number', sa.String(length=100), nullable=False, comment='Unique certificate number.'),
    sa.Column('certificate_url', sa.String(length=500), nullable=True, comment='URL of the generated certificate.'),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Date and time when the certificate was issued.'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_certificates_course_courses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_certificates_student_users', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_certificates'),
    sa.UniqueConstraint('certificate_number', name='uq_certificates_certificate_number'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_certificates_student_course'),
    comment='Stores certificates issued after course completion.'
    )
    op.create_index('ix_certificates_course_id', 'certificates', ['course_id'], unique=False)
    op.create_index('ix_certificates_issued_at', 'certificates', ['issued_at'], unique=False)
    op.create_index('ix_certificates_student_id', 'certificates', ['student_id'], unique=False)
    op.create_table('course_reviews',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the review.'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='Course being reviewed.'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='Student who submitted the review.'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating given by the student (1 to 5).'),
    sa.Column('review', sa.Text(), nullable=True, comment='Written review provided by the student.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this review record.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the review was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated the review.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the review was last updated.'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_course_reviews_rating'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_course_reviews_course_courses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_course_reviews_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_course_reviews_student_users', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_course_reviews_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_course_reviews'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_course_reviews_course_student')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the enrollment.'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='Student enrolled in the course.'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='Course in which the student is enrolled.'),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='enrollment_status_enum'), nullable=False, comment='Current enrollment status.'),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Enrollment date.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Course start date.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Course completion date.'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_enrollments_course_courses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_enrollments_student_users', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_enrollments'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollments_student_course')
    )
    op.create_index('ix_enrollments_course_id', 'enrollments', ['course_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the module.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Module title.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Module description.'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='Course that owns this module.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the module is active.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the module.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Module creation timestamp.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated the module.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Module last update timestamp.'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_modules_course_id_courses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_modules_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_modules_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_modules')
    )
    op.create_index('ix_modules_course_id', 'modules', ['course_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the payment.'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='Student who made the payment.'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='Course purchased by the student.'),
    sa.Column('transaction_id', sa.String(length=100), nullable=False, comment='Unique transaction identifier from the payment gateway.'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Amount paid.'),
    sa.Column('payment_method', sa.String(length=50), nullable=False, comment='Payment method used.'),
    sa.Column('payment_gateway', sa.String(length=50), nullable=True, comment='Payment gateway used (Stripe, Razorpay, PayPal, etc.).'),
    sa.Column('payment_status', sa.String(length=30), nullable=False, comment='Current payment status.'),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True, comment='Date and time the payment was completed.'),
    sa.Column('currency', sa.String(length=10), server_default='INR', nullable=True, comment='Currency used for the transaction.'),
    sa.Column('receipt_url', sa.String(length=500), nullable=True, comment='URL of the payment receipt.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the payment record.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the payment record was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated the payment record.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the payment record was last updated.'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_payments_course_courses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_payments_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_payments_student_users', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_payments_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_payments'),
    sa.UniqueConstraint('transaction_id', name='uq_payments_transaction_id')
    )
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the lesson.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Lesson title.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Lesson description.'),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='Video URL associated with the lesson.'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Display order of the lesson within the module.'),
    sa.Column('module_id', sa.UUID(), nullable=False, comment='Module that owns this lesson.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates whether the lesson is active.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this lesson.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the lesson was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated this lesson.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the lesson was last updated.'),
    sa.CheckConstraint('position > 0', name='ck_lessons_position_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_lessons_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name='fk_lessons_module_id_modules', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_lessons_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_lessons'),
    sa.UniqueConstraint('module_id', 'position', name='uq_lessons_module_position'),
    comment='Stores lessons that belong to a module.'
    )
    op.create_index('ix_lessons_created_by', 'lessons', ['created_by'], unique=False)
    op.create_index('ix_lessons_is_active', 'lessons', ['is_active'], unique=False)
    op.create_index('ix_lessons_module_active', 'lessons', ['module_id', 'is_active'], unique=False)
    op.create_index('ix_lessons_module_id', 'lessons', ['module_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the quiz.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Quiz title.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Quiz description.'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='Course associated with the quiz.'),
    sa.Column('lesson_id', sa.UUID(), nullable=True, comment='Lesson associated with the quiz.'),
    sa.Column('total_marks', sa.Integer(), nullable=True, comment='Maximum marks for the quiz.'),
    sa.Column('pass_marks', sa.Integer(), nullable=True, comment='Minimum marks required to pass.'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Quiz duration in minutes.'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the quiz is active.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the quiz.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Quiz creation timestamp.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated the quiz.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Quiz last update timestamp.'),
    sa.CheckConstraint('duration > 0', name='ck_quizzes_duration_positive'),
    sa.CheckConstraint('pass_marks <= total_marks', name='ck_quizzes_pass_marks_valid'),
    sa.CheckConstraint('pass_marks >= 0', name='ck_quizzes_pass_marks_positive'),
    sa.CheckConstraint('total_marks >= 0', name='ck_quizzes_total_marks'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='fk_quizzes_course_courses', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_quizzes_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name='fk_quizzes_lesson_lessons', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_quizzes_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_quizzes')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the quiz attempt.'),
    sa.Column('quiz_id', sa.UUID(), nullable=False, comment='Quiz attempted by the student.'),
    sa.Column('student_id', sa.UUID(), nullable=False, comment='Student who attempted the quiz.'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Score obtained in the quiz.'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Time when the quiz attempt started.'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Time when the quiz attempt was completed.'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='quiz_attempt_status_enum'), nullable=False, comment='Current status of the quiz attempt.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this attempt record.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Attempt creation timestamp.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated the attempt.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Attempt last update timestamp.'),
    sa.CheckConstraint('score >= 0', name='ck_quiz_attempts_score_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_quiz_attempts_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='fk_quiz_attempts_quiz_quizzes', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='fk_quiz_attempts_student_users', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_quiz_attempts_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_quiz_attempts')
    )
    op.create_index('ix_quiz_attempts_quiz_id', 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the quiz question.'),
    sa.Column('quiz_id', sa.UUID(), nullable=False, comment='Quiz to which this question belongs.'),
    sa.Column('position', sa.Integer(), nullable=False, comment='Display order of the question within the quiz.'),
    sa.Column('question', sa.Text(), nullable=False, comment='Question text.'),
    sa.Column('option_a', sa.String(length=255), nullable=True, comment='Option A.'),
    sa.Column('option_b', sa.String(length=255), nullable=True, comment='Option B.'),
    sa.Column('option_c', sa.String(length=255), nullable=True, comment='Option C.'),
    sa.Column('option_d', sa.String(length=255), nullable=True, comment='Option D.'),
    sa.Column('correct_option', sa.CHAR(length=1), nullable=False, comment='Correct option (A, B, C or D).'),
    sa.Column('marks', sa.Integer(), nullable=False, comment='Marks awarded for the correct answer.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created the question.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Question creation timestamp.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated the question.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Question last update timestamp.'),
    sa.CheckConstraint("correct_option IN ('A','B','C','D')", name='ck_quiz_questions_correct_option'),
    sa.CheckConstraint('marks > 0', name='ck_quiz_questions_marks_positive'),
    sa.CheckConstraint('position > 0', name='ck_quiz_questions_position_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_quiz_questions_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='fk_quiz_questions_quiz_quizzes', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_quiz_questions_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_quiz_questions'),
    sa.UniqueConstraint('quiz_id', 'position', name='uq_quiz_questions_position')
    )
    op.create_index('ix_quiz_questions_quiz_id', 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key of the quiz answer.'),
    sa.Column('attempt_id', sa.UUID(), nullable=False, comment='Quiz attempt associated with this answer.'),
    sa.Column('question_id', sa.UUID(), nullable=False, comment='Question answered by the student.'),
    sa.Column('selected_option', sa.CHAR(length=1), nullable=True, comment='Option selected by the student (A, B, C or D).'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='Indicates whether the selected answer is correct.'),
    sa.Column('marks_obtained', sa.Numeric(precision=5, scale=2), nullable=True, comment='Marks awarded for this answer.'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this record.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the answer was created.'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='User who last updated this record.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the answer was last updated.'),
    sa.CheckConstraint("selected_option IN ('A','B','C','D')", name='ck_quiz_answers_selected_option'),
    sa.CheckConstraint('marks_obtained >= 0', name='ck_quiz_answers_marks_positive'),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], name='fk_quiz_answers_attempt_quiz_attempts', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_quiz_answers_created_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name='fk_quiz_answers_question_quiz_questions', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_quiz_answers_updated_by_users', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_quiz_answers'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_quiz_answers_attempt_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers')
    op.drop_index('ix_quiz_questions_quiz_id', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index('ix_quiz_attempts_quiz_id', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_table('quizzes')
    op.drop_index('ix_lessons_module_id', table_name='lessons')
    op.drop_index('ix_lessons_module_active', table_name='lessons')
    op.drop_index('ix_lessons_is_active', table_name='lessons')
    op.drop_index('ix_lessons_created_by', table_name='lessons')
    op.drop_table('lessons')
    op.drop_table('payments')
    op.drop_index('ix_modules_course_id', table_name='modules')
    op.drop_table('modules')
    op.drop_index('ix_enrollments_course_id', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('course_reviews')
    op.drop_index('ix_certificates_student_id', table_name='certificates')
    op.drop_index('ix_certificates_issued_at', table_name='certificates')
    op.drop_index('ix_certificates_course_id', table_name='certificates')
    op.drop_table('certificates')
    op.drop_index('ix_courses_title', table_name='courses')
    op.drop_index('ix_courses_category_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
