"""create all tables

Revision ID: 973ca843e506
Revises: 35d22c5134e2
Create Date: 2026-07-21 15:51:02.846002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973ca843e506'
down_revision: Union[str, Sequence[str], None] = '35d22c5134e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_roles_updated_by_users', 'roles', 'users', ['updated_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_roles_created_by_users', 'roles', 'users', ['created_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_roles_created_by_users', 'roles', type_='foreignkey')
    op.drop_constraint('fk_roles_updated_by_users', 'roles', type_='foreignkey')
    # ### end Alembic commands ###
