"""remove the position column in quiz question table

Revision ID: f0b8dfe20896
Revises: 0f8b3e6fb8b8
Create Date: 2026-07-23 16:16:28.764948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0b8dfe20896'
down_revision: Union[str, Sequence[str], None] = '0f8b3e6fb8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_quiz_questions_position'), 'quiz_questions', type_='unique')
    op.drop_column('quiz_questions', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False, comment='Display order of the question within the quiz.'))
    op.create_unique_constraint(op.f('uq_quiz_questions_position'), 'quiz_questions', ['quiz_id', 'position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
